export function LanguagesAndToolsCard() {
  return (
    <div className={"card card-compact bg-base-100 shadow-xl"}>
      <div className={"card-body"}>
        <div className={"flex-container"}>
          <img
            className={"image-link"}
            alt={"java"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg"
          />
          <img
            className={"image-link"}
            alt={"kotlin"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg"
          />
          <img
            className={"image-link"}
            alt={"android"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg"
          />
          <img
            className={"image-link"}
            alt={"python"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg"
          />
          <img
            className={"image-link"}
            alt={"unity"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg"
          />

          <img
            className={"image-link"}
            alt={"c#"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg"
          />
          <img
            className={"image-link"}
            alt={".net"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dot-net/dot-net-original.svg"
          />
          <img
            className={"image-link"}
            alt={"javascript"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"
          />
          <img
            className={"image-link"}
            alt={"html"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg"
          />
          <img
            className={"image-link"}
            alt={"css"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg"
          />
          <img
            className={"image-link"}
            alt={"react"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg"
          />
          <img
            className={"image-link"}
            alt={"nodejs"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg"
          />
          <img
            className={"image-link"}
            alt={"figma"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg"
          />
          <img
            className={"image-link"}
            alt={"docker"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg"
          />
          <img
            className={"image-link"}
            alt={"mysql"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg"
          />
          <img
            className={"image-link"}
            alt={"postgres"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg"
          />
          <img
            className={"image-link"}
            alt={"mongodb"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg"
          />
          <img
            className={"image-link"}
            alt={"git"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg"
          />
          <img
            className={"image-link"}
            alt={"github"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg"
          />
          <img
            className={"image-link"}
            alt={"adobe illustrator"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg"
          />
          <img
            className={"image-link"}
            alt={"adobe photoshop"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg"
          />
          <img
            className={"image-link"}
            alt={"adobe premiere"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/premierepro/premierepro-plain.svg"
          />
          <img
            className={"image-link"}
            alt={"jira"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg"
          />
          <img
            className={"image-link"}
            alt={"vscode"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg"
          />
          <img
            className={"image-link"}
            alt={"visual studio"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/visualstudio/visualstudio-plain.svg"
          />
          <img
            className={"image-link"}
            alt={"intelliJ"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/intellij/intellij-original.svg"
          />
          <img
            className={"image-link"}
            alt={"jetbrains"}
            src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jetbrains/jetbrains-original.svg"
          />
        </div>
      </div>
    </div>
  );
}
